# Ch2.0 NumPy Basics

In [3]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.14.0'

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [3]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array

In [4]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [5]:
ar1

array([0, 1, 2, 3])

In [6]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [7]:
#ar2.shape
ar2.shape

(2, 3)

In [8]:
#ar2.ndim
ar2.ndim

2

## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [9]:
#ar3=np.arange(12); ar3
ar3=np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
# start, end (exclusive)
#ar4=np.arange(3,10,3); ar4
ar4=np.arange(3,10,3)
ar4

array([3, 6, 9])

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [11]:
# args - start element,end element, number of elements
#ar5=np.linspace(0,2.0/3,4); ar5
ar5=np.linspace(0,2.0/3,4)
ar5

array([0.        , 0.22222222, 0.44444444, 0.66666667])

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [12]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.zeros

In [13]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.eye

In [14]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.diag

In [15]:
# Create diagonal array
ar10=np.diag((2,1,4,6)); ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [16]:
# Using the rand, randn functions
# rand(m) produces uniformly distributed random numbers with range 0 to m
np.random.seed(200) # Set seed
ar11=np.random.rand(3); ar11

array([0.94763226, 0.22654742, 0.59442014])

In [17]:
# randn(m) produces m normally distributed (Gaussian) random numbers
ar12=np.random.randn(5); ar12

array([ 1.4983231 , -0.40666493, -0.09376948,  0.87472083,  0.83141749])

### numpy.empty

In [18]:
ar13=np.empty((3,2)); ar13

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [19]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');
ar

array([ 2., -1.,  6.,  3.])

In [20]:
ar.dtype

dtype('float64')

In [21]:
ar=np.array([2,4,6,8]); ar.dtype

dtype('int32')

In [22]:
ar=np.array([2.,4,6,8]); ar.dtype

dtype('float64')

In [23]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype

dtype('<U9')

In [24]:
bar=np.array([True, False, True]); bar.dtype

dtype('bool')

In [25]:
f_ar = np.array([3,-2,8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [26]:
f_ar.astype(int)

array([ 3, -2,  8])

## NumPy indexing and slicing

In [27]:
# print entire array, element 0, element 1, last element.
ar = np.arange(5); print(ar); ar[0], ar[1], ar[-1]

[0 1 2 3 4]


(0, 1, 4)

In [28]:
# 2nd, last and 1st elements
ar=np.arange(5); ar[1], ar[-1], ar[0]

(1, 4, 0)

In [29]:
# Reverse array using ::-1 idiom
ar=np.arange(5); ar[::-1]

array([4, 3, 2, 1, 0])

In [30]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [31]:
ar[1,1]

8

In [32]:
ar[1,1]=5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

In [33]:
# Retrieve row 2
ar[2]

array([11, 12, 13])

In [34]:
ar[2,:]

array([11, 12, 13])

In [35]:
# Retrieve column 1
ar[:,1]

array([ 3,  5, 12])

### Fancy Indexing

In [36]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [37]:
# access three different elements
[x[3], x[7], x[2]]

[71, 86, 14]

In [38]:
# pass a single list or array of indices to obtain the same result
ind = [3, 7, 2]
x[ind]

array([71, 86, 14])

In [39]:
x[[3,7,2]]

array([71, 86, 14])

##  Array slicing
Arrays can be sliced using the following syntax:<br>
ar[startIndex: endIndex: stepValue].

In [40]:
ar=2*np.arange(6); ar

array([ 0,  2,  4,  6,  8, 10])

In [41]:
ar[1:5:2]

array([2, 6])

In [42]:
# if we wish to include the endIndex value, we need to go above it
ar[1:6:2] 

array([ 2,  6, 10])

In [43]:
ar[:4]

array([0, 2, 4, 6])

In [44]:
ar[4:]

array([ 8, 10])

In [45]:
# Slice array with stepValue=3
ar[::3]

array([0, 6])

Assignment and slicing can be combined as shown in the following code snippet:

In [46]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [47]:
ar[:3]=1; ar

array([ 1,  1,  1,  6,  8, 10])

In [48]:
ar[2:]=np.ones(4);ar

array([1, 1, 1, 1, 1, 1])

## Array masking

In [49]:
np.random.seed(10)
ar=np.random.randint(0,25,10); ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [50]:
evenMask=(ar % 2==0); evenMask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [51]:
evenNums=ar[evenMask]; evenNums

array([ 4,  0, 16,  8,  0])

To eliminate missing values

In [23]:
ar=np.array(['Hungary','Nigeria',
'Guatemala','','Poland','','Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [24]:
np.count_nonzero(ar=='')

2

In [25]:
ar[ar=='']='USA'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

## Copies and views

<b>Modifying view modifies original array</b>

In [54]:
ar1=np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
ar2=ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [56]:
ar2[1]=-1; ar1

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

<b>Use np.copy to force a copy</b><br>

In [57]:
ar=np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
arc=ar[:3].copy(); arc

array([0, 1, 2])

In [59]:
arc[0]=-1; arc

array([-1,  1,  2])

In [60]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])