# Ch2.1 NumPy Operations

# Operations

## Basic Operations

In [2]:
import numpy as np
import pandas as pd

In [2]:
ar=np.arange(0,7)*5; ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [3]:
ar=np.arange(5) ** 4 ; ar

array([  0,   1,  16,  81, 256], dtype=int32)

In [4]:
ar ** 0.5

array([ 0.,  1.,  4.,  9., 16.])

In [5]:
ar=3+np.arange(0, 30,3); ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [6]:
ar2=np.arange(1,11); ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
ar+ar2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [8]:
ar-ar2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
ar/ar2

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [10]:
ar*ar2

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

<b>Array multiplication is element wise</b><br>

In [11]:
ar=np.array([[1,1],[1,1]]); ar

array([[1, 1],
       [1, 1]])

In [12]:
ar2=np.array([[2,2],[2,2]]); ar2

array([[2, 2],
       [2, 2]])

In [13]:
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

In [14]:
ar*ar2

array([[2, 2],
       [2, 2]])

<b>Comparison and logical operations are also elememt-wise</b>

In [15]:
ar=np.arange(1,5); ar

array([1, 2, 3, 4])

In [16]:
ar2=np.arange(5,1,-1); ar2

array([5, 4, 3, 2])

In [17]:
ar < ar2

array([ True,  True, False, False])

In [3]:
l1 = np.array([True,False,True,False])
l2 = np.array([False,False,True, True])
np.logical_and(l1,l2)

array([False, False,  True, False])

In [5]:
np.logical_or(l1,l2)

array([ True, False,  True,  True])

In [4]:
np.logical_xor(l1,l2)

array([ True, False, False,  True])

<b>For element-wise operations, the 2 arrays must be the same shape else an error results</b>

In [19]:
ar=np.arange(0,6); ar

array([0, 1, 2, 3, 4, 5])

In [20]:
ar2=np.arange(0,8); ar2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
ar*ar2

ValueError: operands could not be broadcast together with shapes (6,) (8,) 

<b>NumPy arrays can be transposed</b>

In [8]:
ar=np.array([[1,2,3],[4,5,6]]); ar

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.transpose(ar)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Reduction Operations
Operators such as np.sum and np.prod perform reduces on arrays; that is, they
combine several elements into a single value:

In [27]:
ar=np.arange(1,5)
ar.prod()

24

specify whether the reduction operator to be applied row-wise or column-wise

In [28]:
ar=np.array([np.arange(1,6),np.arange(1,6)]); ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [29]:
#Columns
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [30]:
#Rows
np.prod(ar,axis=1)

array([120, 120])

not specifying an axis results in the operation being applied to all elements of the array

In [12]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]); 
ar.sum()

54

In [10]:
ar.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [11]:
np.median(ar,axis = 1)

array([2., 5.])

## Statistical operators

In [34]:
np.random.seed(10)
ar=np.random.randint(0,10, size=(4,5)); ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [35]:
ar.mean()

4.45

In [15]:
ar.std()

2.581988897471611

In [16]:
ar.std(axis =1)

array([0.81649658, 0.81649658, 0.81649658])

In [17]:
ar.std(axis =0)

array([2.44948974, 2.44948974, 2.44948974])

In [37]:
ar.var(axis=0) #across rows

array([12.6875,  4.1875, 11.    , 10.75  , 18.1875])

## Logical operators

In [39]:
np.random.seed(100)
ar=np.random.randint(1,10, size=(4,4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [18]:
(ar%7)==0

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [40]:
np.any((ar%7)==0)

False

In [19]:
ar<11

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
np.all(ar<11)

True

## Broadcasting

In [42]:
ar=np.ones([3,2]); ar

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
ar2=np.array([2,3]); ar2

array([2, 3])

In [44]:
ar+ar2

array([[3., 4.],
       [3., 4.],
       [3., 4.]])

In [22]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
a+b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [24]:
a

array([1, 2, 3])

In [25]:
b

array([[4],
       [5],
       [6]])

In [27]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
a*b

array([[ 4, 10, 18],
       [ 7, 16, 27],
       [ 1,  4,  9]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array()