In [1]:
import numpy as np ;

In [2]:
A=np.arange(2,14).reshape((3,4))
print('A=\n',A);

A=
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [3]:
print("the max num's index=",np.argmax(A));
print("the min num's index=",np.argmin(A));

the max num's index= 11
the min num's index= 0


In [4]:
print('mean=',np.mean(A));
print('A.mean()=',A.mean());

mean= 7.5
A.mean()= 7.5


In [5]:
print('average=',np.average(A));

average= 7.5


In [6]:
print('A.cumsum()=',A.cumsum());        #累加
print('np.diff(A)=',np.diff(A));        # diff() is np's attribute but not np.array
print('np.median(A)=',np.median(A));

A.cumsum()= [ 2  5  9 14 20 27 35 44 54 65 77 90]
np.diff(A)= [[1 1 1]
 [1 1 1]
 [1 1 1]]
np.median(A)= 7.5


In [7]:
B=np.arange(14,2,-1).reshape((3,4))
print('B=\n',B);
print('np.sort(B)=\n',np.sort(B));
print('np.transpose(B)=\n',np.transpose(B));
print('B.T=\n',B.T);

B=
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
np.sort(B)=
 [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
np.transpose(B)=
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
B.T=
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
