In [1]:
import numpy as np

In [2]:
A=np.array([1,1,1])
B=np.array([2,2,2])

In [3]:
C=np.vstack((B,A))
print('vertical stack:\n',C)
print(A.shape,C.shape)

D=np.hstack((A,B))
print('horizontal stack:\n',D)
print(D.shape)

vertical stack:
 [[2 2 2]
 [1 1 1]]
(3,) (2, 3)
horizontal stack:
 [1 1 1 2 2 2]
(6,)


In [4]:
print('A[np.newaxis,:]=',A[np.newaxis,:],
      '\nA[np.newaxis,:].shape:',A[np.newaxis,:].shape)

print('A[:,np.newaxis,:]=\n',A[:,np.newaxis],
      '\nA[:,np.newaxis].shape:',A[:,np.newaxis].shape)

A[np.newaxis,:]= [[1 1 1]] 
A[np.newaxis,:].shape: (1, 3)
A[:,np.newaxis,:]=
 [[1]
 [1]
 [1]] 
A[:,np.newaxis].shape: (3, 1)


In [5]:
A1=np.array([1,1,1])[np.newaxis,:]
B1=np.array([2,2,2])[np.newaxis,:]
print('A1=',A1)
print('B1=',B1)
C1=np.vstack((A1,B1))
D1=np.hstack((A1,B1))
print(C1,'\n',D1)
print('C1.shape=',C1.shape,'C1.shape=',D1.shape)

A1= [[1 1 1]]
B1= [[2 2 2]]
[[1 1 1]
 [2 2 2]] 
 [[1 1 1 2 2 2]]
C1.shape= (2, 3) C1.shape= (1, 6)


In [6]:
E=np.concatenate((A1,B1,B1,A1),axis=0)
print(E)
F=np.concatenate((A1,B1,B1,A1),axis=1)
print(F)

[[1 1 1]
 [2 2 2]
 [2 2 2]
 [1 1 1]]
[[1 1 1 2 2 2 2 2 2 1 1 1]]
