In [1]:
import numpy as np

In [2]:
A=np.arange(2,14).reshape((3,4))
print('A=\n',A)

A=
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [3]:
print('np.split(A,3,axis=0)=', np.split(A,3,axis=0))
print('np.split(A,2,axis=1)=\n', np.split(A,2,axis=1))

np.split(A,3,axis=0)= [array([[2, 3, 4, 5]]), array([[6, 7, 8, 9]]), array([[10, 11, 12, 13]])]
np.split(A,2,axis=1)=
 [array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[ 4,  5],
       [ 8,  9],
       [12, 13]])]


In [4]:
# wrong way to split
# print('np.split(A,3,axis=1)=', np.split(A,3,axis=1))

np.array_split(A,3,axis=1)=
 [array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[ 4],
       [ 8],
       [12]]), array([[ 5],
       [ 9],
       [13]])]


In [5]:
# use this to fix it
print('np.array_split(A,3,axis=1)=\n', np.array_split(A,3,axis=1))

np.array_split(A,3,axis=1)=
 [array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[ 4],
       [ 8],
       [12]]), array([[ 5],
       [ 9],
       [13]])]


In [6]:
print('np.vsplit(A,3)=',np.vsplit(A,3)) #equal to print(np.split(A, 3, axis=0))
print('np.hsplit(A,2)=\n',np.hsplit(A,2)) #equal to print(np.split(A, 2, axis=1))

np.vsplit(A,3)= [array([[2, 3, 4, 5]]), array([[6, 7, 8, 9]]), array([[10, 11, 12, 13]])]
np.hsplit(A,2)=
 [array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[ 4,  5],
       [ 8,  9],
       [12, 13]])]
